version: "3.8"

services:
  api-restuarants:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - .:/app
      - .:/app/dist/apps/

    command: >
      sh -c "
        cd apps/api-restuarants && \
        npm install || { echo 'unable to install api-restaurants packages'; exit 1; }; \
        npm run build && npm run start:dev
      "


  restuarant-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: >
      sh -c "
        cd apps/restuarant-dashboard && \
        npm install || { echo 'unable to install restuarant-dashboard packages'; exit 1; }; \
        if npm run build; then \
          npm run dev; \
        else \
          echo 'npm run build failed'; exit 1; \
        fi
      "

  prisma:
    image: node:lts-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    command: >
      sh -c "
        apk add --no-cache openssl && \  
        cd apps/api-restuarants && \
        if [ ! -f prisma/schema.prisma ]; then echo 'Error: schema.prisma not found!'; exit 1; fi;
        npx prisma generate && npx prisma db push && npx prisma studio
      "
