services:
  api-restuarants:
    build:
      context: ./apps/api-restuarants
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  restuarant-dashboard:
    build:
      context: ./apps/restuarant-dashboard
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  prisma:
    image: node:lts-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    command: >
      sh -c "
        apk add --no-cache openssl && \  
        cd apps/api-restuarants && \
        if [ ! -f prisma/schema.prisma ]; then echo 'Error: schema.prisma not found!'; exit 1; fi;
        npx prisma generate && npx prisma db push && npx prisma studio
      "
