services:
  app:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "4200:4200" # Assuming restaurant-dashboard runs on port 4200
      - "3000:3000" # Assuming api-restaurants runs on port 3000
    command:
      [
        "sh",
        "-c",
        "npm install && npx nx serve restaurant-dashboard & npx nx serve api-restaurants",
      ]

  prisma:
    image: node:18-alpine
    working_dir: /app/apps/api-restaurants
    volumes:
      - .:/app
    ports:
      - "5555:5555" # Prisma Studio default port
    command: ["sh", "-c", "npx prisma studio"]
